
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\x9c-\xe1\x1c\xd4\xbe_\xda\xd4\xf0 H69\x12\x90'
    
_lr_action_items = {'RPAREN':([1,6,7,9,10,11,12,],[-2,-4,-3,12,-6,-1,-5,]),'STRING':([0,1,2,3,4,5,6,7,8,9,10,11,12,],[1,-2,1,1,1,1,-4,-3,1,1,-6,1,-5,]),'LBRACKET':([0,1,2,3,4,5,6,7,8,9,10,11,12,],[2,-2,2,2,2,2,-4,-3,2,2,-6,2,-5,]),'STAR':([1,3,5,6,7,9,10,11,12,],[-2,6,6,-4,6,6,-6,6,-5,]),'LPAREN':([0,1,2,3,4,5,6,7,8,9,10,11,12,],[4,-2,4,4,4,4,-4,-3,4,4,-6,4,-5,]),'BAR':([1,3,5,6,7,9,10,11,12,],[-2,8,8,-4,-3,8,-6,8,-5,]),'RBRACKET':([1,5,6,7,10,11,12,],[-2,10,-4,-3,-6,-1,-5,]),'$end':([1,3,6,7,10,11,12,],[-2,0,-4,-3,-6,-1,-5,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'re':([0,2,3,4,5,7,8,9,11,],[3,5,7,9,7,7,11,7,7,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> re","S'",1,None,None,None),
  ('re -> re BAR re','re',3,'p_re_bar','/Users/oscarestrada/Dropbox/School/Udacity/Python/Programming_Languages/implementing_re.py',71),
  ('re -> STRING','re',1,'p_re_string','/Users/oscarestrada/Dropbox/School/Udacity/Python/Programming_Languages/implementing_re.py',79),
  ('re -> re re','re',2,'p_re_concat','/Users/oscarestrada/Dropbox/School/Udacity/Python/Programming_Languages/implementing_re.py',84),
  ('re -> re STAR','re',2,'p_exp_star','/Users/oscarestrada/Dropbox/School/Udacity/Python/Programming_Languages/implementing_re.py',89),
  ('re -> LPAREN re RPAREN','re',3,'p_exp_group','/Users/oscarestrada/Dropbox/School/Udacity/Python/Programming_Languages/implementing_re.py',94),
  ('re -> LBRACKET re RBRACKET','re',3,'p_exp_bracket','/Users/oscarestrada/Dropbox/School/Udacity/Python/Programming_Languages/implementing_re.py',99),
]
